INSERT INTO department (id, capacity, name) VALUES
                                                (1, 60, 'Administration'),
                                                (2, 100, 'Accounts'),
                                                (3, 80, 'Computer Science'),
                                                (4, 50, 'Electrical Engineering'),
                                                (5, 30, 'Civil Engineering'),
                                                (6, 120, 'Mechanical Engineering'),
                                                (7, 75, 'Biotechnology'),
                                                (8, 40, 'Environmental Science'),
                                                (9, 90, 'Mathematics'),
                                                (10, 110, 'Physics'),
                                                (11, 60, 'Chemistry'),
                                                (12, 85, 'Pharmacy'),
                                                (13, 95, 'Architecture'),
                                                (14, 50, 'Law'),
                                                (15, 70, 'Business Administration'),
                                                (16, 65, 'Economics'),
                                                (17, 100, 'Sociology'),
                                                (18, 55, 'Psychology'),
                                                (19, 40, 'Fine Arts'),
                                                (20, 80, 'Music and Performing Arts');